[
    {
        "url": "https://api.github.com/repos/alseambusher/Paideia/issues/comments/310248970",
        "html_url": "https://github.com/alseambusher/Paideia/issues/1#issuecomment-310248970",
        "issue_url": "https://api.github.com/repos/alseambusher/Paideia/issues/1",
        "id": 310248970,
        "node_id": "MDEyOklzc3VlQ29tbWVudDMxMDI0ODk3MA==",
        "user": {
            "login": "LtveG",
            "id": 28047736,
            "node_id": "MDQ6VXNlcjI4MDQ3NzM2",
            "avatar_url": "https://avatars3.githubusercontent.com/u/28047736?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/LtveG",
            "html_url": "https://github.com/LtveG",
            "followers_url": "https://api.github.com/users/LtveG/followers",
            "following_url": "https://api.github.com/users/LtveG/following{/other_user}",
            "gists_url": "https://api.github.com/users/LtveG/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/LtveG/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/LtveG/subscriptions",
            "organizations_url": "https://api.github.com/users/LtveG/orgs",
            "repos_url": "https://api.github.com/users/LtveG/repos",
            "events_url": "https://api.github.com/users/LtveG/events{/privacy}",
            "received_events_url": "https://api.github.com/users/LtveG/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2017-06-22T01:21:06Z",
        "updated_at": "2017-06-22T01:21:06Z",
        "author_association": "NONE",
        "body": "I have the same error....Do you solve it?"
    },
    {
        "url": "https://api.github.com/repos/alseambusher/Paideia/issues/comments/410955603",
        "html_url": "https://github.com/alseambusher/Paideia/issues/1#issuecomment-410955603",
        "issue_url": "https://api.github.com/repos/alseambusher/Paideia/issues/1",
        "id": 410955603,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQxMDk1NTYwMw==",
        "user": {
            "login": "vivekjm",
            "id": 24496671,
            "node_id": "MDQ6VXNlcjI0NDk2Njcx",
            "avatar_url": "https://avatars1.githubusercontent.com/u/24496671?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vivekjm",
            "html_url": "https://github.com/vivekjm",
            "followers_url": "https://api.github.com/users/vivekjm/followers",
            "following_url": "https://api.github.com/users/vivekjm/following{/other_user}",
            "gists_url": "https://api.github.com/users/vivekjm/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vivekjm/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vivekjm/subscriptions",
            "organizations_url": "https://api.github.com/users/vivekjm/orgs",
            "repos_url": "https://api.github.com/users/vivekjm/repos",
            "events_url": "https://api.github.com/users/vivekjm/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vivekjm/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-08-07T07:04:27Z",
        "updated_at": "2018-08-07T07:04:27Z",
        "author_association": "NONE",
        "body": "i have that same error also..can anyone help me\r\n"
    }
]