[
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/492989310",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-492989310",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 492989310,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5Mjk4OTMxMA==",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-16T09:19:54Z",
        "updated_at": "2019-05-16T09:19:54Z",
        "author_association": "NONE",
        "body": "when I use inference_with_ckpt.py .\r\nI got [ERROR] Failed to load specified weight.\r\nwhy?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493280363",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493280363",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493280363,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzI4MDM2Mw==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T00:55:10Z",
        "updated_at": "2019-05-17T00:59:45Z",
        "author_association": "OWNER",
        "body": "> when I use inference_with_ckpt.py .\r\n> I got [ERROR] Failed to load specified weight.\r\n> why?\r\n\r\nCan you kindly provide:\r\n1. The command you tried\r\n2. Your environment (OS, python version, TF version, and anything related you can think of)\r\n3. The error message\r\n\r\nso we can help you resolve the problem you encountered?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493293303",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493293303",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493293303,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzI5MzMwMw==",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T02:12:50Z",
        "updated_at": "2019-05-17T02:12:50Z",
        "author_association": "NONE",
        "body": "python:3.7.3   tensorflow:'2.0.0-dev20190516'  I can training. After that I got models include checkpoint generator.data-00000-of-00001  generator.index. Then use \u201cpython inference_with_ckpt.py \\\r\n    --m_path models \\\r\n    --img_path 11.png \\\r\n    --out_dir ./1111 \\\r\n    --light\u201d    \r\nI got [ERROR] Failed to load specified weight.\r\n[2019-05-16 19:05:52] [inference] [ERROR] If you trained your model with --light, consider adding --light when executing this script; otherwise, do not add --light when executing this script.\r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493293664",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493293664",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493293664,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzI5MzY2NA==",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T02:14:41Z",
        "updated_at": "2019-05-17T02:14:41Z",
        "author_association": "NONE",
        "body": "conda -V :conda 4.6.14\r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493294338",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493294338",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493294338,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzI5NDMzOA==",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T02:18:42Z",
        "updated_at": "2019-05-17T02:18:42Z",
        "author_association": "NONE",
        "body": "when I play around the ckpts with inference_with_ckpt.py and export.py with light_paprika_ckpt and light_shinkai_ckpt,I got the same error.Why?\r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493384491",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493384491",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493384491,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzM4NDQ5MQ==",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T09:16:18Z",
        "updated_at": "2019-05-17T09:16:18Z",
        "author_association": "NONE",
        "body": "I change python version to 3.6.0 \u3002I got the same error [ERROR] Failed to load specified weight. Can you tell me the reason?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493388078",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493388078",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493388078,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzM4ODA3OA==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T09:27:56Z",
        "updated_at": "2019-05-17T09:27:56Z",
        "author_association": "OWNER",
        "body": "Thank you for reporting. I think the problem is that our script only accepts RGB image. When it comes to RGBA image, TF engine raises `ValueError` since the model does not accept RGBA (4-channel) image.\r\n\r\nWe fixed this issue in [12500080](https://github.com/mnicnc404/CartoonGan-tensorflow/commit/12500080ffeaf945a914e41aefc596988d8f053a).\r\n\r\nThank you again for letting us know!\r\n\r\n> when I play around the ckpts with inference_with_ckpt.py and export.py with light_paprika_ckpt and light_shinkai_ckpt,I got the same error.Why?\r\n\r\nAs for `export.py`, can you kindly pull the latest master branch and provide the command and the error message so we can know how to resolve the problem?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493389695",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493389695",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493389695,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzM4OTY5NQ==",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T09:33:12Z",
        "updated_at": "2019-05-17T09:33:12Z",
        "author_association": "NONE",
        "body": "So do I need to use RGB images when I train?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493391675",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493391675",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493391675,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzM5MTY3NQ==",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T09:39:29Z",
        "updated_at": "2019-05-17T09:39:29Z",
        "author_association": "NONE",
        "body": "when I run export.py ,I got the error \"TypeError: 'NoneType' object is not callable\r\n\"  "
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493392592",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493392592",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493392592,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzM5MjU5Mg==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T09:42:18Z",
        "updated_at": "2019-05-17T09:42:36Z",
        "author_association": "OWNER",
        "body": "> So do I need to use RGB images when I train?\r\n\r\nEither RGB (e.g., jpg) or RGBA (e.g., png) is OK when it comes to `train.py`. See `train.py` L202:\r\n\r\n`x = tf.image.decode_jpeg(x, channels=3)`\r\n\r\nAccording to TF doc, `tf.image.decode_jpg` supports jpg, png, and non-animated gif. The `channels=3` infers that this function call returns a tensor which has only 3 channels."
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493393892",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493393892",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493393892,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzM5Mzg5Mg==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T09:46:22Z",
        "updated_at": "2019-05-17T09:46:22Z",
        "author_association": "OWNER",
        "body": "> when I run export.py ,I got the error \"TypeError: 'NoneType' object is not callable\r\n> \"\r\n\r\nCan you provide the full stack trace?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493398056",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493398056",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493398056,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzM5ODA1Ng==",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T10:00:13Z",
        "updated_at": "2019-05-17T10:00:13Z",
        "author_association": "NONE",
        "body": "I use \"python3 export.py     --m_path ./light_shinkai_ckpt    --out_dir ./1111     --light\"\r\nThen I got \r\n [export] [INFO] tensorflowjs_converter --input_format tf_saved_model --output_format tfjs_graph_model ./1111/SavedModelLight_0018 ./1111/tfjs_model_light_0018\r\nWriting weight file ./1111/tfjs_model_light_0018/model.json...\r\nException ignored in: <bound method _EagerDefinedFunctionDeleter.__del__ of <tensorflow.python.eager.function._EagerDefinedFunctionDeleter object at 0x7f471a2da9b0>>\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 305, in __del__\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py\", line 1639, in remove_function\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py\", line 863, in remove_function\r\nTypeError: 'NoneType' object is not callable\r\nException ignored in: <bound method _EagerDefinedFunctionDeleter.__del__ of <tensorflow.python.eager.function._EagerDefinedFunctionDeleter object at 0x7f47196d1d68>>\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 305, in __del__\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py\", line 1639, in remove_function\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py\", line 863, in remove_function\r\nTypeError: 'NoneType' object is not callable\r\nException ignored in: <bound method _EagerDefinedFunctionDeleter.__del__ of <tensorflow.python.eager.function._EagerDefinedFunctionDeleter object at 0x7f471868a358>>\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 305, in __del__\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py\", line 1639, in remove_function\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py\", line 863, in remove_function\r\nTypeError: 'NoneType' object is not callable\r\nException ignored in: <bound method _EagerDefinedFunctionDeleter.__del__ of <tensorflow.python.eager.function._EagerDefinedFunctionDeleter object at 0x7f47186292e8>>\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 305, in __del__\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py\", line 1639, in remove_function\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py\", line 863, in remove_function\r\nTypeError: 'NoneType' object is not callable\r\n\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493410229",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493410229",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493410229,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzQxMDIyOQ==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-17T10:44:52Z",
        "updated_at": "2019-05-17T10:55:59Z",
        "author_association": "OWNER",
        "body": "> tensorflowjs_converter\r\n\r\nThis problem is caused by `tensorflowjs_converter`, referring to [https://github.com/tensorflow/tfjs/issues/1582](https://github.com/tensorflow/tfjs/issues/1582):\r\n\r\n> This model is saved with TF2.0 alpha, but loaded with 2.0 nightly, there could be some mismatch there.\r\n\r\nCurrently we can not solve this issue since we are not tfjs developers, but can you try the environment we provided by executing the following command:\r\n\r\n```\r\n# assuming you're using conda\r\n# make sure you're in CartoonGan-tensorflow\r\nconda env create -n cartoongan -f environment_cpu.yml  # or environment_gpu.yml if you have gpu instance(s)\r\n```\r\n\r\nAnd run `train.py` and`export.py` again? I think it shall resolve the issue."
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/493643967",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/11#issuecomment-493643967",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/11",
        "id": 493643967,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5MzY0Mzk2Nw==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-18T03:17:28Z",
        "updated_at": "2019-05-18T03:17:28Z",
        "author_association": "OWNER",
        "body": "I'm closing this issue since we are not tfjs developers and thus cannot fix the tfjs version mismatch problem."
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/496441684",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/12#issuecomment-496441684",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/12",
        "id": 496441684,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NjQ0MTY4NA==",
        "user": {
            "login": "leemengtaiwan",
            "id": 3454980,
            "node_id": "MDQ6VXNlcjM0NTQ5ODA=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/3454980?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/leemengtaiwan",
            "html_url": "https://github.com/leemengtaiwan",
            "followers_url": "https://api.github.com/users/leemengtaiwan/followers",
            "following_url": "https://api.github.com/users/leemengtaiwan/following{/other_user}",
            "gists_url": "https://api.github.com/users/leemengtaiwan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/leemengtaiwan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/leemengtaiwan/subscriptions",
            "organizations_url": "https://api.github.com/users/leemengtaiwan/orgs",
            "repos_url": "https://api.github.com/users/leemengtaiwan/repos",
            "events_url": "https://api.github.com/users/leemengtaiwan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/leemengtaiwan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-28T09:35:26Z",
        "updated_at": "2019-05-28T09:35:26Z",
        "author_association": "COLLABORATOR",
        "body": "Hi, thanks for trying out our code and the cute image!\r\n\r\nIn order to achieve what you want, it would be better if you try some other GANs which can generate images from scratch (e.g, from a random distribution). \r\n\r\nIn CartoonGAN (and our implementation), the goal is to make some small changes to make the image \"cartoon-like\", rather than transform the images dramatically.\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/496473396",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/12#issuecomment-496473396",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/12",
        "id": 496473396,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NjQ3MzM5Ng==",
        "user": {
            "login": "guoqian0097282",
            "id": 8876075,
            "node_id": "MDQ6VXNlcjg4NzYwNzU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/8876075?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoqian0097282",
            "html_url": "https://github.com/guoqian0097282",
            "followers_url": "https://api.github.com/users/guoqian0097282/followers",
            "following_url": "https://api.github.com/users/guoqian0097282/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoqian0097282/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoqian0097282/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoqian0097282/subscriptions",
            "organizations_url": "https://api.github.com/users/guoqian0097282/orgs",
            "repos_url": "https://api.github.com/users/guoqian0097282/repos",
            "events_url": "https://api.github.com/users/guoqian0097282/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoqian0097282/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-05-28T11:16:16Z",
        "updated_at": "2019-05-28T11:16:16Z",
        "author_association": "NONE",
        "body": "OK,thank you!!"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/497915147",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/13#issuecomment-497915147",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/13",
        "id": 497915147,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NzkxNTE0Nw==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-01T05:34:12Z",
        "updated_at": "2019-06-01T05:34:12Z",
        "author_association": "OWNER",
        "body": "It seems to me that the color is not beyond expectation, depending on your dataset. My model trained with Paprika tends to generate reddish images since most images of the dataset are reddish. Your model generates yellowish images for the same reason.\r\nYou can try reducing the weight of style loss `--style_lambda`, but by doing so the training process might take a longer time."
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/497915205",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/14#issuecomment-497915205",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/14",
        "id": 497915205,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NzkxNTIwNQ==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-01T05:35:36Z",
        "updated_at": "2019-06-01T05:35:36Z",
        "author_association": "OWNER",
        "body": "Can you kindly provide your conda version, pip version, and OS?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/497989875",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/14#issuecomment-497989875",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/14",
        "id": 497989875,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5Nzk4OTg3NQ==",
        "user": {
            "login": "changbaishan",
            "id": 12687044,
            "node_id": "MDQ6VXNlcjEyNjg3MDQ0",
            "avatar_url": "https://avatars2.githubusercontent.com/u/12687044?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/changbaishan",
            "html_url": "https://github.com/changbaishan",
            "followers_url": "https://api.github.com/users/changbaishan/followers",
            "following_url": "https://api.github.com/users/changbaishan/following{/other_user}",
            "gists_url": "https://api.github.com/users/changbaishan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/changbaishan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/changbaishan/subscriptions",
            "organizations_url": "https://api.github.com/users/changbaishan/orgs",
            "repos_url": "https://api.github.com/users/changbaishan/repos",
            "events_url": "https://api.github.com/users/changbaishan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/changbaishan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-02T01:13:54Z",
        "updated_at": "2019-06-02T01:13:54Z",
        "author_association": "NONE",
        "body": "Hi, thank you very much for the response!\r\nconda 4.6.14\r\npip 18.1 from /home/comp/anaconda3/lib/python3.7/site-packages/pip (python 3.7)\r\nDistributor ID:\tUbuntu\r\nDescription:\tUbuntu 18.04.2 LTS\r\nRelease:\t18.04\r\nCodename:\tbionic\r\n\r\nPlease help so I can proceed forward, I like your software. \r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/498085692",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/14#issuecomment-498085692",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/14",
        "id": 498085692,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODA4NTY5Mg==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-03T01:37:05Z",
        "updated_at": "2019-06-10T00:52:57Z",
        "author_association": "OWNER",
        "body": "Sorry, I cannot reproduce the error. Can you try installing all the dependencies manually?\r\n\r\n```\r\nconda create -n cartoongan conda python=3.6 numpy mkl imageio pillow tqdm\r\n# skip mkl if you're not using intel CPU\r\nconda activate cartoongan\r\npip install tensorflow==2.0.0a tf-nightly-2.0-preview tensorflowjs\r\ngit clone https://www.github.com/keras-team/keras-contrib.git \\\r\n    && cd keras-contrib \\\r\n    && python convert_to_tf_keras.py \\\r\n    && USE_TF_KERAS=1 python setup.py install\r\n```"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/498085803",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/13#issuecomment-498085803",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/13",
        "id": 498085803,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODA4NTgwMw==",
        "user": {
            "login": "TachibanaYoshino",
            "id": 36946777,
            "node_id": "MDQ6VXNlcjM2OTQ2Nzc3",
            "avatar_url": "https://avatars0.githubusercontent.com/u/36946777?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TachibanaYoshino",
            "html_url": "https://github.com/TachibanaYoshino",
            "followers_url": "https://api.github.com/users/TachibanaYoshino/followers",
            "following_url": "https://api.github.com/users/TachibanaYoshino/following{/other_user}",
            "gists_url": "https://api.github.com/users/TachibanaYoshino/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TachibanaYoshino/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TachibanaYoshino/subscriptions",
            "organizations_url": "https://api.github.com/users/TachibanaYoshino/orgs",
            "repos_url": "https://api.github.com/users/TachibanaYoshino/repos",
            "events_url": "https://api.github.com/users/TachibanaYoshino/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TachibanaYoshino/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-03T01:38:00Z",
        "updated_at": "2019-06-03T01:38:00Z",
        "author_association": "NONE",
        "body": "When I reduce the weight of the style loss, such as 10.0 or 15.0, I find that the generated image has almost no cartoon style, even when training to 100 epcoh.\r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/498086925",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/13#issuecomment-498086925",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/13",
        "id": 498086925,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ5ODA4NjkyNQ==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-03T01:46:51Z",
        "updated_at": "2019-06-03T01:46:51Z",
        "author_association": "OWNER",
        "body": "I don't have your dataset so I can only give advices that might not help. If that's the case, increase the content loss lambda and see if it helps.\r\n\r\nIn fact, in the original CartoonGan paper, they didn't even use style loss. If you really want to train a model that generates images without color distortion, you may set style-lambda to 0 and a larger g_adv_lambda. If that does not help, I suggest consulting the authors of the CartoonGan paper.\r\n\r\nClosing the issue since not much help I can provide."
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/500260182",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/14#issuecomment-500260182",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/14",
        "id": 500260182,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUwMDI2MDE4Mg==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-10T00:56:40Z",
        "updated_at": "2019-06-10T00:56:40Z",
        "author_association": "OWNER",
        "body": "I have updated our yaml file. Please try the following command:\r\n```\r\nconda env create -f environment_linux_cpu.yml\r\n```"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/500273565",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/14#issuecomment-500273565",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/14",
        "id": 500273565,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUwMDI3MzU2NQ==",
        "user": {
            "login": "changbaishan",
            "id": 12687044,
            "node_id": "MDQ6VXNlcjEyNjg3MDQ0",
            "avatar_url": "https://avatars2.githubusercontent.com/u/12687044?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/changbaishan",
            "html_url": "https://github.com/changbaishan",
            "followers_url": "https://api.github.com/users/changbaishan/followers",
            "following_url": "https://api.github.com/users/changbaishan/following{/other_user}",
            "gists_url": "https://api.github.com/users/changbaishan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/changbaishan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/changbaishan/subscriptions",
            "organizations_url": "https://api.github.com/users/changbaishan/orgs",
            "repos_url": "https://api.github.com/users/changbaishan/repos",
            "events_url": "https://api.github.com/users/changbaishan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/changbaishan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-10T02:40:56Z",
        "updated_at": "2019-06-10T02:40:56Z",
        "author_association": "NONE",
        "body": "Thank you very much for your recent release!\r\n\r\nconda env create -n cartoongan -f environment_linux_cpu.yml works out great.\r\n\r\nHowever, when I test with \r\n\r\npython cartoonize.py --input_dir input_images  --output_dir output_images --styles shinkai hayao --comparison_view horizontal\r\nTraceback (most recent call last):\r\n  File \"cartoonize.py\", line 11, in <module>\r\n    from style_transfer.cartoongan import cartoongan\r\n  File \"/home/myself/Documents/sandbox/playground/testtwo/CartoonGan-tensorflow/style_transfer/cartoongan/cartoongan.py\", line 4, in <module>\r\n    from keras_contrib.layers import InstanceNormalization\r\nModuleNotFoundError: No module named 'keras_contrib'\r\n\r\nMay be you need to include that and possible others in the environment_linux_cpu.yml\r\n\r\nThanks very much,  I value your efforts.\r\n"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/500276032",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/14#issuecomment-500276032",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/14",
        "id": 500276032,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUwMDI3NjAzMg==",
        "user": {
            "login": "leemengtaiwan",
            "id": 3454980,
            "node_id": "MDQ6VXNlcjM0NTQ5ODA=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/3454980?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/leemengtaiwan",
            "html_url": "https://github.com/leemengtaiwan",
            "followers_url": "https://api.github.com/users/leemengtaiwan/followers",
            "following_url": "https://api.github.com/users/leemengtaiwan/following{/other_user}",
            "gists_url": "https://api.github.com/users/leemengtaiwan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/leemengtaiwan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/leemengtaiwan/subscriptions",
            "organizations_url": "https://api.github.com/users/leemengtaiwan/orgs",
            "repos_url": "https://api.github.com/users/leemengtaiwan/repos",
            "events_url": "https://api.github.com/users/leemengtaiwan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/leemengtaiwan/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-10T02:58:12Z",
        "updated_at": "2019-06-10T02:58:12Z",
        "author_association": "COLLABORATOR",
        "body": "@changbaishan yap it would be better if we include `keras_contrib` in the env file as well, but right now the easiest way to install `keras_contrib` is by running following command:\r\n\r\n```bash\r\ngit clone https://www.github.com/keras-team/keras-contrib.git \\\r\n    && cd keras-contrib \\\r\n    && python convert_to_tf_keras.py \\\r\n    && USE_TF_KERAS=1 python setup.py install\r\n```\r\n\r\nafter installing `keras_contrib` you should be able to run the script."
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/500279089",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/14#issuecomment-500279089",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/14",
        "id": 500279089,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUwMDI3OTA4OQ==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-10T03:21:23Z",
        "updated_at": "2019-06-10T03:21:23Z",
        "author_association": "OWNER",
        "body": "Currently keras_contrib does not officially offer tf.keras prebuilt package, so unfortunately we can not include this package into our environment yamls.\r\n\r\nClosing the issue since the original problem is solved. Feel free to reopen it if you encounter any other related problems."
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/510932837",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/17#issuecomment-510932837",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/17",
        "id": 510932837,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxMDkzMjgzNw==",
        "user": {
            "login": "HuangDanGeeker",
            "id": 24517481,
            "node_id": "MDQ6VXNlcjI0NTE3NDgx",
            "avatar_url": "https://avatars1.githubusercontent.com/u/24517481?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/HuangDanGeeker",
            "html_url": "https://github.com/HuangDanGeeker",
            "followers_url": "https://api.github.com/users/HuangDanGeeker/followers",
            "following_url": "https://api.github.com/users/HuangDanGeeker/following{/other_user}",
            "gists_url": "https://api.github.com/users/HuangDanGeeker/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/HuangDanGeeker/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/HuangDanGeeker/subscriptions",
            "organizations_url": "https://api.github.com/users/HuangDanGeeker/orgs",
            "repos_url": "https://api.github.com/users/HuangDanGeeker/repos",
            "events_url": "https://api.github.com/users/HuangDanGeeker/events{/privacy}",
            "received_events_url": "https://api.github.com/users/HuangDanGeeker/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-07-12T15:37:54Z",
        "updated_at": "2019-07-12T15:43:16Z",
        "author_association": "NONE",
        "body": "When using```python inference_with_saved_model.py --other_parameters```,\r\nI wander if you @WenheLI  ever have dealed with this problem 'ImportError: cannot import name 'export_saved_model'"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/517880575",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/20#issuecomment-517880575",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/20",
        "id": 517880575,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxNzg4MDU3NQ==",
        "user": {
            "login": "iszotic",
            "id": 22536473,
            "node_id": "MDQ6VXNlcjIyNTM2NDcz",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22536473?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/iszotic",
            "html_url": "https://github.com/iszotic",
            "followers_url": "https://api.github.com/users/iszotic/followers",
            "following_url": "https://api.github.com/users/iszotic/following{/other_user}",
            "gists_url": "https://api.github.com/users/iszotic/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/iszotic/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/iszotic/subscriptions",
            "organizations_url": "https://api.github.com/users/iszotic/orgs",
            "repos_url": "https://api.github.com/users/iszotic/repos",
            "events_url": "https://api.github.com/users/iszotic/events{/privacy}",
            "received_events_url": "https://api.github.com/users/iszotic/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-03T00:50:46Z",
        "updated_at": "2019-08-03T00:50:46Z",
        "author_association": "NONE",
        "body": "you need the generator and discriminator checkpoints, these are not given"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/518137742",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/17#issuecomment-518137742",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/17",
        "id": 518137742,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxODEzNzc0Mg==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-05T08:26:40Z",
        "updated_at": "2019-08-05T08:26:40Z",
        "author_association": "OWNER",
        "body": "> Thanks for your excellent work!\r\n> I got an error of `AttributeError: module 'tensorflow' has no attribute 'get_default_graph` when I try to run your code. It seems to be a dependency issue do you have any clue?\r\n\r\nCan you kindly provide the commands resulting in the error?"
    },
    {
        "url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/comments/518138598",
        "html_url": "https://github.com/mnicnc404/CartoonGan-tensorflow/issues/20#issuecomment-518138598",
        "issue_url": "https://api.github.com/repos/mnicnc404/CartoonGan-tensorflow/issues/20",
        "id": 518138598,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxODEzODU5OA==",
        "user": {
            "login": "mnicnc404",
            "id": 2225912,
            "node_id": "MDQ6VXNlcjIyMjU5MTI=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/2225912?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mnicnc404",
            "html_url": "https://github.com/mnicnc404",
            "followers_url": "https://api.github.com/users/mnicnc404/followers",
            "following_url": "https://api.github.com/users/mnicnc404/following{/other_user}",
            "gists_url": "https://api.github.com/users/mnicnc404/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mnicnc404/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mnicnc404/subscriptions",
            "organizations_url": "https://api.github.com/users/mnicnc404/orgs",
            "repos_url": "https://api.github.com/users/mnicnc404/repos",
            "events_url": "https://api.github.com/users/mnicnc404/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mnicnc404/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-05T08:29:28Z",
        "updated_at": "2019-08-05T08:29:28Z",
        "author_association": "OWNER",
        "body": "> I fail to load the trained model to finetune, which is in the file of light_shinkai_ckpt. It shows that\r\n> \u2018Checkpoint is not found, training from scratch with 1 epochs...\u2019\r\n\r\nCan you kindly provide the command generating the info?"
    }
]