[
    {
        "url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/comments/419890573",
        "html_url": "https://github.com/smarx/ethshardingpoc/pull/2#issuecomment-419890573",
        "issue_url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/2",
        "id": 419890573,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQxOTg5MDU3Mw==",
        "user": {
            "login": "timbeiko",
            "id": 9390255,
            "node_id": "MDQ6VXNlcjkzOTAyNTU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/9390255?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/timbeiko",
            "html_url": "https://github.com/timbeiko",
            "followers_url": "https://api.github.com/users/timbeiko/followers",
            "following_url": "https://api.github.com/users/timbeiko/following{/other_user}",
            "gists_url": "https://api.github.com/users/timbeiko/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/timbeiko/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/timbeiko/subscriptions",
            "organizations_url": "https://api.github.com/users/timbeiko/orgs",
            "repos_url": "https://api.github.com/users/timbeiko/repos",
            "events_url": "https://api.github.com/users/timbeiko/events{/privacy}",
            "received_events_url": "https://api.github.com/users/timbeiko/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-10T12:10:32Z",
        "updated_at": "2018-09-10T12:10:32Z",
        "author_association": "COLLABORATOR",
        "body": "Simplified a bunch of the simulator file, but now we are getting a bunch of web3 errors because of Python 2.7 is used in the project and Web3 requires >3.5. @maurelian @smarx What do you think is the best thing to do here? Should we merge this in now and fix the Python 2 vs. 3 issue in a separate PR?  "
    },
    {
        "url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/comments/420795812",
        "html_url": "https://github.com/smarx/ethshardingpoc/issues/3#issuecomment-420795812",
        "issue_url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/3",
        "id": 420795812,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMDc5NTgxMg==",
        "user": {
            "login": "maurelian",
            "id": 23033765,
            "node_id": "MDQ6VXNlcjIzMDMzNzY1",
            "avatar_url": "https://avatars3.githubusercontent.com/u/23033765?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maurelian",
            "html_url": "https://github.com/maurelian",
            "followers_url": "https://api.github.com/users/maurelian/followers",
            "following_url": "https://api.github.com/users/maurelian/following{/other_user}",
            "gists_url": "https://api.github.com/users/maurelian/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maurelian/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maurelian/subscriptions",
            "organizations_url": "https://api.github.com/users/maurelian/orgs",
            "repos_url": "https://api.github.com/users/maurelian/repos",
            "events_url": "https://api.github.com/users/maurelian/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maurelian/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-12T20:59:47Z",
        "updated_at": "2018-09-12T20:59:47Z",
        "author_association": "COLLABORATOR",
        "body": "This was a fairly hacky thing we did to get the vm binaries working on both my ubuntu, and Steve's os x machine. \r\n\r\nhttps://github.com/smarx/ethshardingpoc/blob/master/run.py#L18-L20\r\n\r\nDoes it work if you comment out the first two lines, so that it's just `vladvm_path = './vladvm-macos'`?\r\nIt might be better to put that into the config file.\r\n\r\n\r\n\r\n"
    },
    {
        "url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/comments/421049571",
        "html_url": "https://github.com/smarx/ethshardingpoc/issues/3#issuecomment-421049571",
        "issue_url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/3",
        "id": 421049571,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMTA0OTU3MQ==",
        "user": {
            "login": "timbeiko",
            "id": 9390255,
            "node_id": "MDQ6VXNlcjkzOTAyNTU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/9390255?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/timbeiko",
            "html_url": "https://github.com/timbeiko",
            "followers_url": "https://api.github.com/users/timbeiko/followers",
            "following_url": "https://api.github.com/users/timbeiko/following{/other_user}",
            "gists_url": "https://api.github.com/users/timbeiko/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/timbeiko/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/timbeiko/subscriptions",
            "organizations_url": "https://api.github.com/users/timbeiko/orgs",
            "repos_url": "https://api.github.com/users/timbeiko/repos",
            "events_url": "https://api.github.com/users/timbeiko/events{/privacy}",
            "received_events_url": "https://api.github.com/users/timbeiko/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-13T15:31:24Z",
        "updated_at": "2018-09-13T15:31:24Z",
        "author_association": "COLLABORATOR",
        "body": "@maurelian that fixed it, the file runs on my machine now. Do you want me to try and fix those two lines to get the path to be set to `'./vladvm-macos'` if you're on mac? "
    },
    {
        "url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/comments/421058838",
        "html_url": "https://github.com/smarx/ethshardingpoc/issues/3#issuecomment-421058838",
        "issue_url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/3",
        "id": 421058838,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMTA1ODgzOA==",
        "user": {
            "login": "timbeiko",
            "id": 9390255,
            "node_id": "MDQ6VXNlcjkzOTAyNTU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/9390255?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/timbeiko",
            "html_url": "https://github.com/timbeiko",
            "followers_url": "https://api.github.com/users/timbeiko/followers",
            "following_url": "https://api.github.com/users/timbeiko/following{/other_user}",
            "gists_url": "https://api.github.com/users/timbeiko/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/timbeiko/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/timbeiko/subscriptions",
            "organizations_url": "https://api.github.com/users/timbeiko/orgs",
            "repos_url": "https://api.github.com/users/timbeiko/repos",
            "events_url": "https://api.github.com/users/timbeiko/events{/privacy}",
            "received_events_url": "https://api.github.com/users/timbeiko/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-13T15:57:32Z",
        "updated_at": "2018-09-13T15:57:32Z",
        "author_association": "COLLABORATOR",
        "body": "FWIW if I pull @vladzamfir's latest commit (c59a342ba299d35e1069c586a17bb815dfaad923) , things break and I get the following error:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"simulator.py\", line 50, in <module>\r\n    new_message = validators[next_proposer].make_new_consensus_message(rand_ID, data)\r\n  File \"/Users/timbeiko/Code/ethshardingpoc/validator.py\", line 149, in make_new_consensus_message\r\n    new_block = self.make_block(shard_ID, data, TTL)\r\n  File \"/Users/timbeiko/Code/ethshardingpoc/validator.py\", line 129, in make_block\r\n    new_vm_state, new_outgoing_payloads = apply_to_state(prevblock.vm_state, data, newly_received_payloads)\r\n  File \"/Users/timbeiko/Code/ethshardingpoc/run.py\", line 107, in apply_to_state\r\n    result = json.loads(out)\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py\", line 354, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py\", line 339, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py\", line 357, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\nMacBook-Pro-3:ethshardingpoc timbeiko$\r\n```"
    },
    {
        "url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/comments/421114107",
        "html_url": "https://github.com/smarx/ethshardingpoc/issues/3#issuecomment-421114107",
        "issue_url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/3",
        "id": 421114107,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMTExNDEwNw==",
        "user": {
            "login": "timbeiko",
            "id": 9390255,
            "node_id": "MDQ6VXNlcjkzOTAyNTU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/9390255?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/timbeiko",
            "html_url": "https://github.com/timbeiko",
            "followers_url": "https://api.github.com/users/timbeiko/followers",
            "following_url": "https://api.github.com/users/timbeiko/following{/other_user}",
            "gists_url": "https://api.github.com/users/timbeiko/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/timbeiko/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/timbeiko/subscriptions",
            "organizations_url": "https://api.github.com/users/timbeiko/orgs",
            "repos_url": "https://api.github.com/users/timbeiko/repos",
            "events_url": "https://api.github.com/users/timbeiko/events{/privacy}",
            "received_events_url": "https://api.github.com/users/timbeiko/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-13T18:54:19Z",
        "updated_at": "2018-09-13T18:54:19Z",
        "author_association": "COLLABORATOR",
        "body": "Update: after pulling 6f64ce530461e71d32d56f89d8598a2286402ae0 everything works fine if I comment the lines mentioned by @maurelian above. So I think a fix to better check for MacOS vs. Ubuntu would probably help. `simulator.py` runs fine now. "
    },
    {
        "url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/comments/421374397",
        "html_url": "https://github.com/smarx/ethshardingpoc/pull/4#issuecomment-421374397",
        "issue_url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/4",
        "id": 421374397,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMTM3NDM5Nw==",
        "user": {
            "login": "maurelian",
            "id": 23033765,
            "node_id": "MDQ6VXNlcjIzMDMzNzY1",
            "avatar_url": "https://avatars3.githubusercontent.com/u/23033765?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maurelian",
            "html_url": "https://github.com/maurelian",
            "followers_url": "https://api.github.com/users/maurelian/followers",
            "following_url": "https://api.github.com/users/maurelian/following{/other_user}",
            "gists_url": "https://api.github.com/users/maurelian/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maurelian/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maurelian/subscriptions",
            "organizations_url": "https://api.github.com/users/maurelian/orgs",
            "repos_url": "https://api.github.com/users/maurelian/repos",
            "events_url": "https://api.github.com/users/maurelian/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maurelian/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-14T14:22:59Z",
        "updated_at": "2018-09-14T14:22:59Z",
        "author_association": "COLLABORATOR",
        "body": "@timbeiko there's a merge conflict, can you resolve it before we merge this?"
    },
    {
        "url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/comments/421378803",
        "html_url": "https://github.com/smarx/ethshardingpoc/pull/4#issuecomment-421378803",
        "issue_url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/4",
        "id": 421378803,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMTM3ODgwMw==",
        "user": {
            "login": "timbeiko",
            "id": 9390255,
            "node_id": "MDQ6VXNlcjkzOTAyNTU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/9390255?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/timbeiko",
            "html_url": "https://github.com/timbeiko",
            "followers_url": "https://api.github.com/users/timbeiko/followers",
            "following_url": "https://api.github.com/users/timbeiko/following{/other_user}",
            "gists_url": "https://api.github.com/users/timbeiko/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/timbeiko/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/timbeiko/subscriptions",
            "organizations_url": "https://api.github.com/users/timbeiko/orgs",
            "repos_url": "https://api.github.com/users/timbeiko/repos",
            "events_url": "https://api.github.com/users/timbeiko/events{/privacy}",
            "received_events_url": "https://api.github.com/users/timbeiko/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-14T14:37:12Z",
        "updated_at": "2018-09-14T14:37:12Z",
        "author_association": "COLLABORATOR",
        "body": "@maurelian done. Merging."
    },
    {
        "url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/comments/421391960",
        "html_url": "https://github.com/smarx/ethshardingpoc/issues/5#issuecomment-421391960",
        "issue_url": "https://api.github.com/repos/smarx/ethshardingpoc/issues/5",
        "id": 421391960,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMTM5MTk2MA==",
        "user": {
            "login": "timbeiko",
            "id": 9390255,
            "node_id": "MDQ6VXNlcjkzOTAyNTU=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/9390255?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/timbeiko",
            "html_url": "https://github.com/timbeiko",
            "followers_url": "https://api.github.com/users/timbeiko/followers",
            "following_url": "https://api.github.com/users/timbeiko/following{/other_user}",
            "gists_url": "https://api.github.com/users/timbeiko/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/timbeiko/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/timbeiko/subscriptions",
            "organizations_url": "https://api.github.com/users/timbeiko/orgs",
            "repos_url": "https://api.github.com/users/timbeiko/repos",
            "events_url": "https://api.github.com/users/timbeiko/events{/privacy}",
            "received_events_url": "https://api.github.com/users/timbeiko/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-14T15:17:59Z",
        "updated_at": "2018-09-14T15:17:59Z",
        "author_association": "COLLABORATOR",
        "body": "Pulled again at a6f229d259fd8d7a4b8f6fa933201778c95e6a7a and I seem to be getting errors from time to time based on the `assert` statements. Is it possible we're sometime sending invalid messages, @vladzamfir ? \r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"simulator.py\", line 65, in <module>\r\n    new_message = validators[next_proposer].make_new_consensus_message(rand_ID, mempools, drain_amount=MEMPOOL_DRAIN_RATE)\r\n  File \"/Users/timbeiko/Code/ethshardingpoc/validator.py\", line 189, in make_new_consensus_message\r\n    new_block = self.make_block(shard_ID, mempools, drain_amount, TTL)\r\n  File \"/Users/timbeiko/Code/ethshardingpoc/validator.py\", line 181, in make_block\r\n    return Block(shard_ID, prevblock, new_txn_log, sent_log, received_log, new_vm_state)\r\n  File \"/Users/timbeiko/Code/ethshardingpoc/blocks.py\", line 104, in __init__\r\n    assert check[0], check[1]\r\nAssertionError: expected all expired sent messages to be received by source\r\n```"
    }
]