[
    {
        "id": 1467698757,
        "node_id": "MDExOkNsb3NlZEV2ZW50MTQ2NzY5ODc1Nw==",
        "url": "https://api.github.com/repos/cdeguzman95/AABot/issues/events/1467698757",
        "actor": {
            "login": "phoenicyan",
            "id": 5103930,
            "node_id": "MDQ6VXNlcjUxMDM5MzA=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/5103930?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/phoenicyan",
            "html_url": "https://github.com/phoenicyan",
            "followers_url": "https://api.github.com/users/phoenicyan/followers",
            "following_url": "https://api.github.com/users/phoenicyan/following{/other_user}",
            "gists_url": "https://api.github.com/users/phoenicyan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/phoenicyan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/phoenicyan/subscriptions",
            "organizations_url": "https://api.github.com/users/phoenicyan/orgs",
            "repos_url": "https://api.github.com/users/phoenicyan/repos",
            "events_url": "https://api.github.com/users/phoenicyan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/phoenicyan/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "closed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-02-09T23:11:03Z",
        "issue": {
            "url": "https://api.github.com/repos/cdeguzman95/AABot/issues/1",
            "repository_url": "https://api.github.com/repos/cdeguzman95/AABot",
            "labels_url": "https://api.github.com/repos/cdeguzman95/AABot/issues/1/labels{/name}",
            "comments_url": "https://api.github.com/repos/cdeguzman95/AABot/issues/1/comments",
            "events_url": "https://api.github.com/repos/cdeguzman95/AABot/issues/1/events",
            "html_url": "https://github.com/cdeguzman95/AABot/issues/1",
            "id": 295384864,
            "node_id": "MDU6SXNzdWUyOTUzODQ4NjQ=",
            "number": 1,
            "title": "Not working on Windows",
            "user": {
                "login": "phoenicyan",
                "id": 5103930,
                "node_id": "MDQ6VXNlcjUxMDM5MzA=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/5103930?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/phoenicyan",
                "html_url": "https://github.com/phoenicyan",
                "followers_url": "https://api.github.com/users/phoenicyan/followers",
                "following_url": "https://api.github.com/users/phoenicyan/following{/other_user}",
                "gists_url": "https://api.github.com/users/phoenicyan/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/phoenicyan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/phoenicyan/subscriptions",
                "organizations_url": "https://api.github.com/users/phoenicyan/orgs",
                "repos_url": "https://api.github.com/users/phoenicyan/repos",
                "events_url": "https://api.github.com/users/phoenicyan/events{/privacy}",
                "received_events_url": "https://api.github.com/users/phoenicyan/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 6,
            "created_at": "2018-02-08T04:51:19Z",
            "updated_at": "2018-02-09T23:11:03Z",
            "closed_at": "2018-02-09T23:11:03Z",
            "author_association": "NONE",
            "body": "I tried to launch bot.py on Windows (python 3.6), but the following error was returned:\r\nPS F:\\Src\\AABot-master> python .\\bot.py\r\nTraceback (most recent call last):\r\n  File \".\\bot.py\", line 1, in <module>\r\n    from airport_info.airports import *\r\n  File \"F:\\Src\\AABot-master\\airport_info\\airports.py\", line 13, in <module>\r\n    for row in reader:\r\n  File \"C:\\Python36\\lib\\encodings\\cp1252.py\", line 23, in decode\r\n    return codecs.charmap_decode(input,self.errors,decoding_table)[0]\r\nUnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 2098: character maps to <undefined>\r\n\r\nAny ideas?"
        }
    }
]