[
    {
        "id": 2907634280,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDI5MDc2MzQyODA=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2907634280",
        "actor": {
            "login": "JeffSaa",
            "id": 11526875,
            "node_id": "MDQ6VXNlcjExNTI2ODc1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/11526875?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/JeffSaa",
            "html_url": "https://github.com/JeffSaa",
            "followers_url": "https://api.github.com/users/JeffSaa/followers",
            "following_url": "https://api.github.com/users/JeffSaa/following{/other_user}",
            "gists_url": "https://api.github.com/users/JeffSaa/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/JeffSaa/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/JeffSaa/subscriptions",
            "organizations_url": "https://api.github.com/users/JeffSaa/orgs",
            "repos_url": "https://api.github.com/users/JeffSaa/repos",
            "events_url": "https://api.github.com/users/JeffSaa/events{/privacy}",
            "received_events_url": "https://api.github.com/users/JeffSaa/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-12-25T06:32:38Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/26",
            "id": 312907778,
            "node_id": "MDU6SXNzdWUzMTI5MDc3Nzg=",
            "number": 26,
            "title": "ValueError",
            "user": {
                "login": "Kazusasukina",
                "id": 28039210,
                "node_id": "MDQ6VXNlcjI4MDM5MjEw",
                "avatar_url": "https://avatars0.githubusercontent.com/u/28039210?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Kazusasukina",
                "html_url": "https://github.com/Kazusasukina",
                "followers_url": "https://api.github.com/users/Kazusasukina/followers",
                "following_url": "https://api.github.com/users/Kazusasukina/following{/other_user}",
                "gists_url": "https://api.github.com/users/Kazusasukina/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Kazusasukina/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Kazusasukina/subscriptions",
                "organizations_url": "https://api.github.com/users/Kazusasukina/orgs",
                "repos_url": "https://api.github.com/users/Kazusasukina/repos",
                "events_url": "https://api.github.com/users/Kazusasukina/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Kazusasukina/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 3,
            "created_at": "2018-04-10T12:49:15Z",
            "updated_at": "2019-12-25T06:32:38Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "$ python main.py \"C:\\Users\\Kazusasukina\\PycharmProjects\\Image-Super-Resolution-master\\results\\lenna.bmp\" --model=ddsr\r\nD:\\environment\\python\\python35\\lib\\site-packages\\h5py\\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\r\n  from ._conv import register_converters as _register_converters\r\nUsing TensorFlow backend.\r\nOld Size :  (512, 512, 3)\r\nNew Size : (1024, 1024, 3)\r\nNumber of patches = 1034289, Patch Shape = (8, 8)\r\nSaving intermediate image.\r\nTraceback (most recent call last):\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 686, in _call_cpp_shape_fn_impl\r\n    input_tensors_as_shapes, status)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\errors_impl.py\", line 473, in __exit__\r\n    c_api.TF_GetCode(self.status.status))\r\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [3,3,3,64], [3,3,64,3].\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"main.py\", line 57, in <module>\r\n    model.upscale(p, save_intermediate=save, mode=mode, patch_size=patch_size, suffix=suffix)\r\n  File \"C:\\Users\\Kazusasukina\\PycharmProjects\\Image-Super-Resolution-master\\models.py\", line 202, in upscale\r\n    model = self.create_model(img_dim_2, img_dim_1, load_weights=True)\r\n  File \"C:\\Users\\Kazusasukina\\PycharmProjects\\Image-Super-Resolution-master\\models.py\", line 659, in create_model\r\n    if load_weights: model.load_weights(self.weight_path)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\keras\\engine\\topology.py\", line 2656, in load_weights\r\n    f, self.layers, reshape=reshape)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\keras\\engine\\topology.py\", line 3382, in load_weights_from_hdf5_group\r\n    K.batch_set_value(weight_value_tuples)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 2368, in batch_set_value\r\n    assign_op = x.assign(assign_placeholder)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 573, in assign\r\n    return state_ops.assign(self._variable, value, use_locking=use_locking)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\ops\\state_ops.py\", line 276, in assign\r\n    validate_shape=validate_shape)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\ops\\gen_state_ops.py\", line 56, in assign\r\n    use_locking=use_locking, name=name)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\r\n    op_def=op_def)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2958, in create_op\r\n    set_shapes_for_outputs(ret)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2209, in set_shapes_for_outputs\r\n    shapes = shape_func(op)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2159, in call_with_requiring\r\n    return call_cpp_shape_fn(op, require_shape_fn=True)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 627, in call_cpp_shape_fn\r\n    require_shape_fn)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 691, in _call_cpp_shape_fn_impl\r\n    raise ValueError(err.message)\r\nValueError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [3,3,3,64], [3,3,64,3].\r\n\r\nI  came across this problem and had no idea about how to figure this out @titu1994 ,may you help~ thanks"
        }
    },
    {
        "id": 2907634279,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MjkwNzYzNDI3OQ==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2907634279",
        "actor": {
            "login": "JeffSaa",
            "id": 11526875,
            "node_id": "MDQ6VXNlcjExNTI2ODc1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/11526875?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/JeffSaa",
            "html_url": "https://github.com/JeffSaa",
            "followers_url": "https://api.github.com/users/JeffSaa/followers",
            "following_url": "https://api.github.com/users/JeffSaa/following{/other_user}",
            "gists_url": "https://api.github.com/users/JeffSaa/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/JeffSaa/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/JeffSaa/subscriptions",
            "organizations_url": "https://api.github.com/users/JeffSaa/orgs",
            "repos_url": "https://api.github.com/users/JeffSaa/repos",
            "events_url": "https://api.github.com/users/JeffSaa/events{/privacy}",
            "received_events_url": "https://api.github.com/users/JeffSaa/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-12-25T06:32:38Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/26/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/26",
            "id": 312907778,
            "node_id": "MDU6SXNzdWUzMTI5MDc3Nzg=",
            "number": 26,
            "title": "ValueError",
            "user": {
                "login": "Kazusasukina",
                "id": 28039210,
                "node_id": "MDQ6VXNlcjI4MDM5MjEw",
                "avatar_url": "https://avatars0.githubusercontent.com/u/28039210?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Kazusasukina",
                "html_url": "https://github.com/Kazusasukina",
                "followers_url": "https://api.github.com/users/Kazusasukina/followers",
                "following_url": "https://api.github.com/users/Kazusasukina/following{/other_user}",
                "gists_url": "https://api.github.com/users/Kazusasukina/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Kazusasukina/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Kazusasukina/subscriptions",
                "organizations_url": "https://api.github.com/users/Kazusasukina/orgs",
                "repos_url": "https://api.github.com/users/Kazusasukina/repos",
                "events_url": "https://api.github.com/users/Kazusasukina/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Kazusasukina/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 3,
            "created_at": "2018-04-10T12:49:15Z",
            "updated_at": "2019-12-25T06:32:38Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "$ python main.py \"C:\\Users\\Kazusasukina\\PycharmProjects\\Image-Super-Resolution-master\\results\\lenna.bmp\" --model=ddsr\r\nD:\\environment\\python\\python35\\lib\\site-packages\\h5py\\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\r\n  from ._conv import register_converters as _register_converters\r\nUsing TensorFlow backend.\r\nOld Size :  (512, 512, 3)\r\nNew Size : (1024, 1024, 3)\r\nNumber of patches = 1034289, Patch Shape = (8, 8)\r\nSaving intermediate image.\r\nTraceback (most recent call last):\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 686, in _call_cpp_shape_fn_impl\r\n    input_tensors_as_shapes, status)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\errors_impl.py\", line 473, in __exit__\r\n    c_api.TF_GetCode(self.status.status))\r\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [3,3,3,64], [3,3,64,3].\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"main.py\", line 57, in <module>\r\n    model.upscale(p, save_intermediate=save, mode=mode, patch_size=patch_size, suffix=suffix)\r\n  File \"C:\\Users\\Kazusasukina\\PycharmProjects\\Image-Super-Resolution-master\\models.py\", line 202, in upscale\r\n    model = self.create_model(img_dim_2, img_dim_1, load_weights=True)\r\n  File \"C:\\Users\\Kazusasukina\\PycharmProjects\\Image-Super-Resolution-master\\models.py\", line 659, in create_model\r\n    if load_weights: model.load_weights(self.weight_path)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\keras\\engine\\topology.py\", line 2656, in load_weights\r\n    f, self.layers, reshape=reshape)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\keras\\engine\\topology.py\", line 3382, in load_weights_from_hdf5_group\r\n    K.batch_set_value(weight_value_tuples)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 2368, in batch_set_value\r\n    assign_op = x.assign(assign_placeholder)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 573, in assign\r\n    return state_ops.assign(self._variable, value, use_locking=use_locking)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\ops\\state_ops.py\", line 276, in assign\r\n    validate_shape=validate_shape)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\ops\\gen_state_ops.py\", line 56, in assign\r\n    use_locking=use_locking, name=name)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\r\n    op_def=op_def)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2958, in create_op\r\n    set_shapes_for_outputs(ret)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2209, in set_shapes_for_outputs\r\n    shapes = shape_func(op)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2159, in call_with_requiring\r\n    return call_cpp_shape_fn(op, require_shape_fn=True)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 627, in call_cpp_shape_fn\r\n    require_shape_fn)\r\n  File \"D:\\environment\\python\\python35\\lib\\site-packages\\tensorflow\\python\\framework\\common_shapes.py\", line 691, in _call_cpp_shape_fn_impl\r\n    raise ValueError(err.message)\r\nValueError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [3,3,3,64], [3,3,64,3].\r\n\r\nI  came across this problem and had no idea about how to figure this out @titu1994 ,may you help~ thanks"
        }
    },
    {
        "id": 2634946907,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDI2MzQ5NDY5MDc=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2634946907",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-09-15T23:44:04Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/28",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/28/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/28/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/28/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/28",
            "id": 329749838,
            "node_id": "MDU6SXNzdWUzMjk3NDk4Mzg=",
            "number": 28,
            "title": "ValueError: could not broadcast input array from shape (32,32,3) into shape (64,64,3)",
            "user": {
                "login": "cycheuk",
                "id": 32156981,
                "node_id": "MDQ6VXNlcjMyMTU2OTgx",
                "avatar_url": "https://avatars1.githubusercontent.com/u/32156981?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/cycheuk",
                "html_url": "https://github.com/cycheuk",
                "followers_url": "https://api.github.com/users/cycheuk/followers",
                "following_url": "https://api.github.com/users/cycheuk/following{/other_user}",
                "gists_url": "https://api.github.com/users/cycheuk/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/cycheuk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/cycheuk/subscriptions",
                "organizations_url": "https://api.github.com/users/cycheuk/orgs",
                "repos_url": "https://api.github.com/users/cycheuk/repos",
                "events_url": "https://api.github.com/users/cycheuk/events{/privacy}",
                "received_events_url": "https://api.github.com/users/cycheuk/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 3,
            "created_at": "2018-06-06T07:46:15Z",
            "updated_at": "2019-09-15T23:44:04Z",
            "closed_at": "2018-06-08T08:18:16Z",
            "author_association": "NONE",
            "body": "Hello there, I also encountered this problem.\r\nTraceback (most recent call last):\r\n  File \"tests.py\", line 47, in <module>\r\n    sr.fit(nb_epochs=250)\r\n  File \"/home/tensor/Checuk/Image-Super-Resolution/models.py\", line 516, in fit\r\n    return super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\n  File \"/home/tensor/Cheuk/Image-Super-Resolution/models.py\", line 122, in fit\r\n    validation_steps=val_count // batch_size + 1)\r\n  File \"/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py\", line 91, in wrapper\r\n    return func(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.5/dist-packages/keras/engine/training.py\", line 2194, in fit_generator\r\n    generator_output = next(output_generator)\r\n  File \"/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py\", line 793, in get\r\n    six.reraise(value.__class__, value, value.__traceback__)\r\n  File \"/usr/local/lib/python3.5/dist-packages/six.py\", line 693, in reraise\r\n    raise value\r\n  File \"/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py\", line 658, in _data_generator_task\r\n    generator_output = next(self._generator)\r\n  File \"/home/tensor/Cheuk/Image-Super-Resolution/img_utils.py\", line 301, in image_generator\r\n    batch_x[i] = img\r\nValueError: could not broadcast input array from shape (32,32,3) into shape (64,64,3)\r\n\r\nI tried to change the def create_model, but it didn't help, and I also tried to change the parameters of the img_utils. \r\nIf you have time, please help me fix this problem. Thanks."
        }
    },
    {
        "id": 2634946905,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MjYzNDk0NjkwNQ==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2634946905",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-09-15T23:44:04Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/28",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/28/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/28/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/28/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/28",
            "id": 329749838,
            "node_id": "MDU6SXNzdWUzMjk3NDk4Mzg=",
            "number": 28,
            "title": "ValueError: could not broadcast input array from shape (32,32,3) into shape (64,64,3)",
            "user": {
                "login": "cycheuk",
                "id": 32156981,
                "node_id": "MDQ6VXNlcjMyMTU2OTgx",
                "avatar_url": "https://avatars1.githubusercontent.com/u/32156981?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/cycheuk",
                "html_url": "https://github.com/cycheuk",
                "followers_url": "https://api.github.com/users/cycheuk/followers",
                "following_url": "https://api.github.com/users/cycheuk/following{/other_user}",
                "gists_url": "https://api.github.com/users/cycheuk/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/cycheuk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/cycheuk/subscriptions",
                "organizations_url": "https://api.github.com/users/cycheuk/orgs",
                "repos_url": "https://api.github.com/users/cycheuk/repos",
                "events_url": "https://api.github.com/users/cycheuk/events{/privacy}",
                "received_events_url": "https://api.github.com/users/cycheuk/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 3,
            "created_at": "2018-06-06T07:46:15Z",
            "updated_at": "2019-09-15T23:44:04Z",
            "closed_at": "2018-06-08T08:18:16Z",
            "author_association": "NONE",
            "body": "Hello there, I also encountered this problem.\r\nTraceback (most recent call last):\r\n  File \"tests.py\", line 47, in <module>\r\n    sr.fit(nb_epochs=250)\r\n  File \"/home/tensor/Checuk/Image-Super-Resolution/models.py\", line 516, in fit\r\n    return super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\n  File \"/home/tensor/Cheuk/Image-Super-Resolution/models.py\", line 122, in fit\r\n    validation_steps=val_count // batch_size + 1)\r\n  File \"/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py\", line 91, in wrapper\r\n    return func(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.5/dist-packages/keras/engine/training.py\", line 2194, in fit_generator\r\n    generator_output = next(output_generator)\r\n  File \"/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py\", line 793, in get\r\n    six.reraise(value.__class__, value, value.__traceback__)\r\n  File \"/usr/local/lib/python3.5/dist-packages/six.py\", line 693, in reraise\r\n    raise value\r\n  File \"/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py\", line 658, in _data_generator_task\r\n    generator_output = next(self._generator)\r\n  File \"/home/tensor/Cheuk/Image-Super-Resolution/img_utils.py\", line 301, in image_generator\r\n    batch_x[i] = img\r\nValueError: could not broadcast input array from shape (32,32,3) into shape (64,64,3)\r\n\r\nI tried to change the def create_model, but it didn't help, and I also tried to change the parameters of the img_utils. \r\nIf you have time, please help me fix this problem. Thanks."
        }
    },
    {
        "id": 2631666743,
        "node_id": "MDE3OlJlbmFtZWRUaXRsZUV2ZW50MjYzMTY2Njc0Mw==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2631666743",
        "actor": {
            "login": "progmars",
            "id": 4199737,
            "node_id": "MDQ6VXNlcjQxOTk3Mzc=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/4199737?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/progmars",
            "html_url": "https://github.com/progmars",
            "followers_url": "https://api.github.com/users/progmars/followers",
            "following_url": "https://api.github.com/users/progmars/following{/other_user}",
            "gists_url": "https://api.github.com/users/progmars/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/progmars/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/progmars/subscriptions",
            "organizations_url": "https://api.github.com/users/progmars/orgs",
            "repos_url": "https://api.github.com/users/progmars/repos",
            "events_url": "https://api.github.com/users/progmars/events{/privacy}",
            "received_events_url": "https://api.github.com/users/progmars/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "renamed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-09-13T09:02:04Z",
        "rename": {
            "from": "Fix for Keras 2",
            "to": "Fix for newer Keras versions"
        },
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/37",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/37/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/37/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/37/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/37",
            "id": 493213545,
            "node_id": "MDU6SXNzdWU0OTMyMTM1NDU=",
            "number": 37,
            "title": "Fix for newer Keras versions",
            "user": {
                "login": "progmars",
                "id": 4199737,
                "node_id": "MDQ6VXNlcjQxOTk3Mzc=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/4199737?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/progmars",
                "html_url": "https://github.com/progmars",
                "followers_url": "https://api.github.com/users/progmars/followers",
                "following_url": "https://api.github.com/users/progmars/following{/other_user}",
                "gists_url": "https://api.github.com/users/progmars/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/progmars/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/progmars/subscriptions",
                "organizations_url": "https://api.github.com/users/progmars/orgs",
                "repos_url": "https://api.github.com/users/progmars/repos",
                "events_url": "https://api.github.com/users/progmars/events{/privacy}",
                "received_events_url": "https://api.github.com/users/progmars/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 0,
            "created_at": "2019-09-13T09:01:13Z",
            "updated_at": "2019-09-13T09:02:04Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "I got an error:\r\n`AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'`\r\n\r\nIf you want to support newer Keras, then according to this:\r\nhttps://github.com/keras-team/keras/issues/12649\r\nthe method has be renamed to image_data_format."
        }
    },
    {
        "id": 2582724657,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDI1ODI3MjQ2NTc=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2582724657",
        "actor": {
            "login": "Combo819",
            "id": 38422065,
            "node_id": "MDQ6VXNlcjM4NDIyMDY1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/38422065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Combo819",
            "html_url": "https://github.com/Combo819",
            "followers_url": "https://api.github.com/users/Combo819/followers",
            "following_url": "https://api.github.com/users/Combo819/following{/other_user}",
            "gists_url": "https://api.github.com/users/Combo819/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Combo819/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Combo819/subscriptions",
            "organizations_url": "https://api.github.com/users/Combo819/orgs",
            "repos_url": "https://api.github.com/users/Combo819/repos",
            "events_url": "https://api.github.com/users/Combo819/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Combo819/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-08-26T07:10:48Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 2582724655,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MjU4MjcyNDY1NQ==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2582724655",
        "actor": {
            "login": "Combo819",
            "id": 38422065,
            "node_id": "MDQ6VXNlcjM4NDIyMDY1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/38422065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Combo819",
            "html_url": "https://github.com/Combo819",
            "followers_url": "https://api.github.com/users/Combo819/followers",
            "following_url": "https://api.github.com/users/Combo819/following{/other_user}",
            "gists_url": "https://api.github.com/users/Combo819/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Combo819/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Combo819/subscriptions",
            "organizations_url": "https://api.github.com/users/Combo819/orgs",
            "repos_url": "https://api.github.com/users/Combo819/repos",
            "events_url": "https://api.github.com/users/Combo819/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Combo819/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-08-26T07:10:48Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 2582724649,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDI1ODI3MjQ2NDk=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2582724649",
        "actor": {
            "login": "hj950815",
            "id": 38309065,
            "node_id": "MDQ6VXNlcjM4MzA5MDY1",
            "avatar_url": "https://avatars0.githubusercontent.com/u/38309065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hj950815",
            "html_url": "https://github.com/hj950815",
            "followers_url": "https://api.github.com/users/hj950815/followers",
            "following_url": "https://api.github.com/users/hj950815/following{/other_user}",
            "gists_url": "https://api.github.com/users/hj950815/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hj950815/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hj950815/subscriptions",
            "organizations_url": "https://api.github.com/users/hj950815/orgs",
            "repos_url": "https://api.github.com/users/hj950815/repos",
            "events_url": "https://api.github.com/users/hj950815/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hj950815/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-08-26T07:10:48Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 2582724647,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MjU4MjcyNDY0Nw==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2582724647",
        "actor": {
            "login": "hj950815",
            "id": 38309065,
            "node_id": "MDQ6VXNlcjM4MzA5MDY1",
            "avatar_url": "https://avatars0.githubusercontent.com/u/38309065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hj950815",
            "html_url": "https://github.com/hj950815",
            "followers_url": "https://api.github.com/users/hj950815/followers",
            "following_url": "https://api.github.com/users/hj950815/following{/other_user}",
            "gists_url": "https://api.github.com/users/hj950815/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hj950815/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hj950815/subscriptions",
            "organizations_url": "https://api.github.com/users/hj950815/orgs",
            "repos_url": "https://api.github.com/users/hj950815/repos",
            "events_url": "https://api.github.com/users/hj950815/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hj950815/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-08-26T07:10:48Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 2280845807,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDIyODA4NDU4MDc=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2280845807",
        "actor": {
            "login": "Combo819",
            "id": 38422065,
            "node_id": "MDQ6VXNlcjM4NDIyMDY1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/38422065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Combo819",
            "html_url": "https://github.com/Combo819",
            "followers_url": "https://api.github.com/users/Combo819/followers",
            "following_url": "https://api.github.com/users/Combo819/following{/other_user}",
            "gists_url": "https://api.github.com/users/Combo819/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Combo819/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Combo819/subscriptions",
            "organizations_url": "https://api.github.com/users/Combo819/orgs",
            "repos_url": "https://api.github.com/users/Combo819/repos",
            "events_url": "https://api.github.com/users/Combo819/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Combo819/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-04-16T20:19:26Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 2280845804,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MjI4MDg0NTgwNA==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/2280845804",
        "actor": {
            "login": "Combo819",
            "id": 38422065,
            "node_id": "MDQ6VXNlcjM4NDIyMDY1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/38422065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Combo819",
            "html_url": "https://github.com/Combo819",
            "followers_url": "https://api.github.com/users/Combo819/followers",
            "following_url": "https://api.github.com/users/Combo819/following{/other_user}",
            "gists_url": "https://api.github.com/users/Combo819/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Combo819/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Combo819/subscriptions",
            "organizations_url": "https://api.github.com/users/Combo819/orgs",
            "repos_url": "https://api.github.com/users/Combo819/repos",
            "events_url": "https://api.github.com/users/Combo819/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Combo819/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2019-04-16T20:19:26Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1929783021,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDE5Mjk3ODMwMjE=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1929783021",
        "actor": {
            "login": "Combo819",
            "id": 38422065,
            "node_id": "MDQ6VXNlcjM4NDIyMDY1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/38422065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Combo819",
            "html_url": "https://github.com/Combo819",
            "followers_url": "https://api.github.com/users/Combo819/followers",
            "following_url": "https://api.github.com/users/Combo819/following{/other_user}",
            "gists_url": "https://api.github.com/users/Combo819/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Combo819/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Combo819/subscriptions",
            "organizations_url": "https://api.github.com/users/Combo819/orgs",
            "repos_url": "https://api.github.com/users/Combo819/repos",
            "events_url": "https://api.github.com/users/Combo819/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Combo819/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-26T20:36:31Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1929783020,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MTkyOTc4MzAyMA==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1929783020",
        "actor": {
            "login": "Combo819",
            "id": 38422065,
            "node_id": "MDQ6VXNlcjM4NDIyMDY1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/38422065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Combo819",
            "html_url": "https://github.com/Combo819",
            "followers_url": "https://api.github.com/users/Combo819/followers",
            "following_url": "https://api.github.com/users/Combo819/following{/other_user}",
            "gists_url": "https://api.github.com/users/Combo819/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Combo819/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Combo819/subscriptions",
            "organizations_url": "https://api.github.com/users/Combo819/orgs",
            "repos_url": "https://api.github.com/users/Combo819/repos",
            "events_url": "https://api.github.com/users/Combo819/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Combo819/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-26T20:36:31Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1929783018,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDE5Mjk3ODMwMTg=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1929783018",
        "actor": {
            "login": "hj950815",
            "id": 38309065,
            "node_id": "MDQ6VXNlcjM4MzA5MDY1",
            "avatar_url": "https://avatars0.githubusercontent.com/u/38309065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hj950815",
            "html_url": "https://github.com/hj950815",
            "followers_url": "https://api.github.com/users/hj950815/followers",
            "following_url": "https://api.github.com/users/hj950815/following{/other_user}",
            "gists_url": "https://api.github.com/users/hj950815/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hj950815/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hj950815/subscriptions",
            "organizations_url": "https://api.github.com/users/hj950815/orgs",
            "repos_url": "https://api.github.com/users/hj950815/repos",
            "events_url": "https://api.github.com/users/hj950815/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hj950815/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-26T20:36:31Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1929783017,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MTkyOTc4MzAxNw==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1929783017",
        "actor": {
            "login": "hj950815",
            "id": 38309065,
            "node_id": "MDQ6VXNlcjM4MzA5MDY1",
            "avatar_url": "https://avatars0.githubusercontent.com/u/38309065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hj950815",
            "html_url": "https://github.com/hj950815",
            "followers_url": "https://api.github.com/users/hj950815/followers",
            "following_url": "https://api.github.com/users/hj950815/following{/other_user}",
            "gists_url": "https://api.github.com/users/hj950815/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hj950815/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hj950815/subscriptions",
            "organizations_url": "https://api.github.com/users/hj950815/orgs",
            "repos_url": "https://api.github.com/users/hj950815/repos",
            "events_url": "https://api.github.com/users/hj950815/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hj950815/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-26T20:36:31Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1909617111,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDE5MDk2MTcxMTE=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1909617111",
        "actor": {
            "login": "Combo819",
            "id": 38422065,
            "node_id": "MDQ6VXNlcjM4NDIyMDY1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/38422065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Combo819",
            "html_url": "https://github.com/Combo819",
            "followers_url": "https://api.github.com/users/Combo819/followers",
            "following_url": "https://api.github.com/users/Combo819/following{/other_user}",
            "gists_url": "https://api.github.com/users/Combo819/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Combo819/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Combo819/subscriptions",
            "organizations_url": "https://api.github.com/users/Combo819/orgs",
            "repos_url": "https://api.github.com/users/Combo819/repos",
            "events_url": "https://api.github.com/users/Combo819/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Combo819/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-17T13:54:44Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1909617109,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MTkwOTYxNzEwOQ==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1909617109",
        "actor": {
            "login": "Combo819",
            "id": 38422065,
            "node_id": "MDQ6VXNlcjM4NDIyMDY1",
            "avatar_url": "https://avatars1.githubusercontent.com/u/38422065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Combo819",
            "html_url": "https://github.com/Combo819",
            "followers_url": "https://api.github.com/users/Combo819/followers",
            "following_url": "https://api.github.com/users/Combo819/following{/other_user}",
            "gists_url": "https://api.github.com/users/Combo819/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Combo819/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Combo819/subscriptions",
            "organizations_url": "https://api.github.com/users/Combo819/orgs",
            "repos_url": "https://api.github.com/users/Combo819/repos",
            "events_url": "https://api.github.com/users/Combo819/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Combo819/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-17T13:54:44Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1909617103,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDE5MDk2MTcxMDM=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1909617103",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-17T13:54:44Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1909617101,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MTkwOTYxNzEwMQ==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1909617101",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-17T13:54:44Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1907859018,
        "node_id": "MDExOkNsb3NlZEV2ZW50MTkwNzg1OTAxOA==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1907859018",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "closed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-16T20:19:36Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/34",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/34/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/34/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/34/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/34",
            "id": 370767414,
            "node_id": "MDU6SXNzdWUzNzA3Njc0MTQ=",
            "number": 34,
            "title": "->Model syntax error",
            "user": {
                "login": "spikopat",
                "id": 20275542,
                "node_id": "MDQ6VXNlcjIwMjc1NTQy",
                "avatar_url": "https://avatars2.githubusercontent.com/u/20275542?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/spikopat",
                "html_url": "https://github.com/spikopat",
                "followers_url": "https://api.github.com/users/spikopat/followers",
                "following_url": "https://api.github.com/users/spikopat/following{/other_user}",
                "gists_url": "https://api.github.com/users/spikopat/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/spikopat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/spikopat/subscriptions",
                "organizations_url": "https://api.github.com/users/spikopat/orgs",
                "repos_url": "https://api.github.com/users/spikopat/repos",
                "events_url": "https://api.github.com/users/spikopat/events{/privacy}",
                "received_events_url": "https://api.github.com/users/spikopat/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 1,
            "created_at": "2018-10-16T19:38:06Z",
            "updated_at": "2018-10-16T20:19:36Z",
            "closed_at": "2018-10-16T20:19:36Z",
            "author_association": "NONE",
            "body": "Traceback (most recent call last):\r\n  File \"drive/PythonOrtam/SuperResolution/main.py\", line 1, in <module>\r\n    import models\r\n  File \"/content/drive/PythonOrtam/SuperResolution/models.py\", line 70\r\n    def create_model(self, height=32, width=32, channels=3, load_weights=False, batch_size=128) -> Model:\r\n                                                                                                ^\r\nSyntaxError: invalid syntax\r\n\r\n\r\n\r\nTraceback (most recent call last):\r\n  File \"drive/PythonOrtam/SuperResolution/main.py\", line 1, in <module>\r\n    import models\r\n  File \"/content/drive/PythonOrtam/SuperResolution/models.py\", line 277\r\n    def _evaluate(sr_model: BaseSuperResolutionModel, validation_dir, scale_pred=False):\r\n                          ^\r\nSyntaxError: invalid syntax\r\n\r\nI have some errors. Can you help me please?\r\n"
        }
    },
    {
        "id": 1904169077,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDE5MDQxNjkwNzc=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1904169077",
        "actor": {
            "login": "hj950815",
            "id": 38309065,
            "node_id": "MDQ6VXNlcjM4MzA5MDY1",
            "avatar_url": "https://avatars0.githubusercontent.com/u/38309065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hj950815",
            "html_url": "https://github.com/hj950815",
            "followers_url": "https://api.github.com/users/hj950815/followers",
            "following_url": "https://api.github.com/users/hj950815/following{/other_user}",
            "gists_url": "https://api.github.com/users/hj950815/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hj950815/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hj950815/subscriptions",
            "organizations_url": "https://api.github.com/users/hj950815/orgs",
            "repos_url": "https://api.github.com/users/hj950815/repos",
            "events_url": "https://api.github.com/users/hj950815/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hj950815/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-15T13:58:51Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1904169076,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MTkwNDE2OTA3Ng==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1904169076",
        "actor": {
            "login": "hj950815",
            "id": 38309065,
            "node_id": "MDQ6VXNlcjM4MzA5MDY1",
            "avatar_url": "https://avatars0.githubusercontent.com/u/38309065?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hj950815",
            "html_url": "https://github.com/hj950815",
            "followers_url": "https://api.github.com/users/hj950815/followers",
            "following_url": "https://api.github.com/users/hj950815/following{/other_user}",
            "gists_url": "https://api.github.com/users/hj950815/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hj950815/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hj950815/subscriptions",
            "organizations_url": "https://api.github.com/users/hj950815/orgs",
            "repos_url": "https://api.github.com/users/hj950815/repos",
            "events_url": "https://api.github.com/users/hj950815/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hj950815/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-10-15T13:58:51Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/25/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/25",
            "id": 312861051,
            "node_id": "MDU6SXNzdWUzMTI4NjEwNTE=",
            "number": 25,
            "title": "ValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)",
            "user": {
                "login": "shreyaspalve",
                "id": 29245769,
                "node_id": "MDQ6VXNlcjI5MjQ1NzY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/29245769?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shreyaspalve",
                "html_url": "https://github.com/shreyaspalve",
                "followers_url": "https://api.github.com/users/shreyaspalve/followers",
                "following_url": "https://api.github.com/users/shreyaspalve/following{/other_user}",
                "gists_url": "https://api.github.com/users/shreyaspalve/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shreyaspalve/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shreyaspalve/subscriptions",
                "organizations_url": "https://api.github.com/users/shreyaspalve/orgs",
                "repos_url": "https://api.github.com/users/shreyaspalve/repos",
                "events_url": "https://api.github.com/users/shreyaspalve/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shreyaspalve/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 7,
            "created_at": "2018-04-10T10:20:53Z",
            "updated_at": "2019-08-26T09:17:56Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution>python tests.py\r\nUsing TensorFlow backend.\r\n2018-04-10 12:19:18.301435: I C:\\tf_jenkins\\workspace\\rel-win\\M\\windows\\PY\\36\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nTraining model : ImageSuperResolutionModel\r\nEpoch 1/250\r\nFound 364 images.\r\nTraceback (most recent call last):\r\nFile \"tests.py\", line 48, in \r\nsr.fit(nb_epochs=250)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 516, in fit\r\nreturn super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\models.py\", line 122, in fit\r\nvalidation_steps=val_count // batch_size + 1)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\nreturn func(*args, **kwargs)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\engine\\training.py\", line 2192, in fit_generator\r\ngenerator_output = next(output_generator)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 793, in get\r\nsix.reraise(value.class, value, value.traceback)\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\six.py\", line 693, in reraise\r\nraise value\r\nFile \"C:\\Users\\Shreyas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\keras\\utils\\data_utils.py\", line 658, in _data_generator_task\r\ngenerator_output = next(self._generator)\r\nFile \"C:\\Users\\Shreyas\\Image-Super-Resolution\\Image-Super-Resolution\\img_utils.py\", line 300, in image_generator\r\nbatch_x[i] = img.transpose((2, 0, 1))\r\nValueError: could not broadcast input array from shape (3,32,32) into shape (3,64,64)\r\n@titu1994 can you please help for solving this issue?"
        }
    },
    {
        "id": 1839762063,
        "node_id": "MDExOkNsb3NlZEV2ZW50MTgzOTc2MjA2Mw==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1839762063",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "closed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-09-11T22:33:03Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/33",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/33/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/33/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/33/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/33",
            "id": 359242147,
            "node_id": "MDU6SXNzdWUzNTkyNDIxNDc=",
            "number": 33,
            "title": "SyntaxError: invalid syntax in models.py",
            "user": {
                "login": "JianbinGG",
                "id": 42915545,
                "node_id": "MDQ6VXNlcjQyOTE1NTQ1",
                "avatar_url": "https://avatars2.githubusercontent.com/u/42915545?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/JianbinGG",
                "html_url": "https://github.com/JianbinGG",
                "followers_url": "https://api.github.com/users/JianbinGG/followers",
                "following_url": "https://api.github.com/users/JianbinGG/following{/other_user}",
                "gists_url": "https://api.github.com/users/JianbinGG/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/JianbinGG/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/JianbinGG/subscriptions",
                "organizations_url": "https://api.github.com/users/JianbinGG/orgs",
                "repos_url": "https://api.github.com/users/JianbinGG/repos",
                "events_url": "https://api.github.com/users/JianbinGG/events{/privacy}",
                "received_events_url": "https://api.github.com/users/JianbinGG/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 2,
            "created_at": "2018-09-11T22:07:05Z",
            "updated_at": "2018-09-11T23:46:34Z",
            "closed_at": "2018-09-11T22:33:03Z",
            "author_association": "NONE",
            "body": "Hi Titu,\r\n\r\nI got an error when first downloading and runing the main.py, the error is below, where do I miss to setup?\r\n\r\nThanks!\r\nJianbin\r\n\r\n------------\r\nTraceback (most recent call last):\r\n  File \"main.py\", line 1, in <module>\r\n    import models\r\n  File \"/home/jianmin/DL/Super_resolution/Image-Super-Resolution/models.py\", line 70\r\n    def create_model(self, height=32, width=32, channels=3, load_weights=False, batch_size=128) -> Model:\r\n                                                                                                ^\r\nSyntaxError: invalid syntax"
        }
    },
    {
        "id": 1775993944,
        "node_id": "MDExOkNsb3NlZEV2ZW50MTc3NTk5Mzk0NA==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1775993944",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "closed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-08-07T18:27:29Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/32",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/32/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/32/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/32/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/32",
            "id": 348435372,
            "node_id": "MDU6SXNzdWUzNDg0MzUzNzI=",
            "number": 32,
            "title": "Syntax Error in model.py",
            "user": {
                "login": "dascylla",
                "id": 32162297,
                "node_id": "MDQ6VXNlcjMyMTYyMjk3",
                "avatar_url": "https://avatars1.githubusercontent.com/u/32162297?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/dascylla",
                "html_url": "https://github.com/dascylla",
                "followers_url": "https://api.github.com/users/dascylla/followers",
                "following_url": "https://api.github.com/users/dascylla/following{/other_user}",
                "gists_url": "https://api.github.com/users/dascylla/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/dascylla/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/dascylla/subscriptions",
                "organizations_url": "https://api.github.com/users/dascylla/orgs",
                "repos_url": "https://api.github.com/users/dascylla/repos",
                "events_url": "https://api.github.com/users/dascylla/events{/privacy}",
                "received_events_url": "https://api.github.com/users/dascylla/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 1,
            "created_at": "2018-08-07T18:24:49Z",
            "updated_at": "2018-08-07T18:27:29Z",
            "closed_at": "2018-08-07T18:27:29Z",
            "author_association": "NONE",
            "body": "I cloned the repo and wanted to run a test image. Thus I entered the following command\r\n\r\n> python2.7 main.py \"/Users/X/PNGs/test_image.png\"\r\n\r\nAnd received the following error message:\r\n\r\n> Traceback (most recent call last):\r\n>   File \"main.py\", line 1, in <module>\r\n>     import models\r\n>   File \"./models.py\", line 70\r\n>     def create_model(self, height=32, width=32, channels=3, load_weights=False, batch_size=128) -> Model:\r\n>                                                                                                 ^\r\n> SyntaxError: invalid syntax\r\n\r\nWhats the meaning here? Obviously the string \"-> Model\" is not part of a regular method definition...\r\n"
        }
    },
    {
        "id": 1684894451,
        "node_id": "MDExOkNsb3NlZEV2ZW50MTY4NDg5NDQ1MQ==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1684894451",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "closed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-06-17T07:53:17Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/30",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/30/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/30/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/30/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/30",
            "id": 333036955,
            "node_id": "MDU6SXNzdWUzMzMwMzY5NTU=",
            "number": 30,
            "title": "expected input_1 to have shape",
            "user": {
                "login": "ManoaNosea",
                "id": 7376591,
                "node_id": "MDQ6VXNlcjczNzY1OTE=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/7376591?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ManoaNosea",
                "html_url": "https://github.com/ManoaNosea",
                "followers_url": "https://api.github.com/users/ManoaNosea/followers",
                "following_url": "https://api.github.com/users/ManoaNosea/following{/other_user}",
                "gists_url": "https://api.github.com/users/ManoaNosea/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ManoaNosea/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ManoaNosea/subscriptions",
                "organizations_url": "https://api.github.com/users/ManoaNosea/orgs",
                "repos_url": "https://api.github.com/users/ManoaNosea/repos",
                "events_url": "https://api.github.com/users/ManoaNosea/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ManoaNosea/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 1,
            "created_at": "2018-06-17T05:34:24Z",
            "updated_at": "2018-06-17T07:53:18Z",
            "closed_at": "2018-06-17T07:53:17Z",
            "author_association": "NONE",
            "body": "```\r\n\u03bb python tests_dsr.py\r\nUsing TensorFlow backend.\r\nTraining model : DenoisingAutoEncoderSR\r\n2018-06-17 08:36:39.645569: I T:\\src\\github\\tensorflow\\tensorflow\\core\\platform\\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\nEpoch 1/250\r\nFound 11156 images.\r\nTraceback (most recent call last):\r\n  File \"tests_dsr.py\", line 63, in <module>\r\n    dsr.fit(nb_epochs=250)\r\n  File \"Y:\\theshitt-backup\\Projects\\AINeuralNetSuperRes\\titu1994\\Image-Super-Resolution-master\\models.py\", line 607, in fit\r\n    return super(DenoisingAutoEncoderSR, self).fit(batch_size, nb_epochs, save_history, history_fn)\r\n  File \"Y:\\theshitt-backup\\Projects\\AINeuralNetSuperRes\\titu1994\\Image-Super-Resolution-master\\models.py\", line 122, in fit\r\n    validation_steps=val_count // batch_size + 1)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\r\n    return func(*args, **kwargs)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training.py\", line 1426, in fit_generator\r\n    initial_epoch=initial_epoch)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training_generator.py\", line 191, in fit_generator\r\n    class_weight=class_weight)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training.py\", line 1214, in train_on_batch\r\n    class_weight=class_weight)\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training.py\", line 754, in _standardize_user_data\r\n    exception_prefix='input')\r\n  File \"C:\\Python35\\lib\\site-packages\\keras\\engine\\training_utils.py\", line 136, in standardize_input_data\r\n    str(data_shape))\r\nValueError: Error when checking input: expected input_1 to have shape (32, 32, 3) but got array with shape (64, 64, 3)\r\n```\r\nwhat the problem ?"
        }
    },
    {
        "id": 1675150602,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDE2NzUxNTA2MDI=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1675150602",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-06-12T00:21:42Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/23",
            "id": 304488708,
            "node_id": "MDU6SXNzdWUzMDQ0ODg3MDg=",
            "number": 23,
            "title": "Requirements",
            "user": {
                "login": "impactcolor",
                "id": 4460178,
                "node_id": "MDQ6VXNlcjQ0NjAxNzg=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/4460178?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/impactcolor",
                "html_url": "https://github.com/impactcolor",
                "followers_url": "https://api.github.com/users/impactcolor/followers",
                "following_url": "https://api.github.com/users/impactcolor/following{/other_user}",
                "gists_url": "https://api.github.com/users/impactcolor/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/impactcolor/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/impactcolor/subscriptions",
                "organizations_url": "https://api.github.com/users/impactcolor/orgs",
                "repos_url": "https://api.github.com/users/impactcolor/repos",
                "events_url": "https://api.github.com/users/impactcolor/events{/privacy}",
                "received_events_url": "https://api.github.com/users/impactcolor/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 10,
            "created_at": "2018-03-12T18:26:44Z",
            "updated_at": "2018-06-12T00:21:42Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "Hi is there any doc on requirements?  I'm running tensor flow with keras and I get errors on both python 2.7 and python 3.5.\r\n\r\nAny help would be appreciated, thank you!"
        }
    },
    {
        "id": 1675150600,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MTY3NTE1MDYwMA==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1675150600",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-06-12T00:21:42Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/23/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/23",
            "id": 304488708,
            "node_id": "MDU6SXNzdWUzMDQ0ODg3MDg=",
            "number": 23,
            "title": "Requirements",
            "user": {
                "login": "impactcolor",
                "id": 4460178,
                "node_id": "MDQ6VXNlcjQ0NjAxNzg=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/4460178?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/impactcolor",
                "html_url": "https://github.com/impactcolor",
                "followers_url": "https://api.github.com/users/impactcolor/followers",
                "following_url": "https://api.github.com/users/impactcolor/following{/other_user}",
                "gists_url": "https://api.github.com/users/impactcolor/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/impactcolor/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/impactcolor/subscriptions",
                "organizations_url": "https://api.github.com/users/impactcolor/orgs",
                "repos_url": "https://api.github.com/users/impactcolor/repos",
                "events_url": "https://api.github.com/users/impactcolor/events{/privacy}",
                "received_events_url": "https://api.github.com/users/impactcolor/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 10,
            "created_at": "2018-03-12T18:26:44Z",
            "updated_at": "2018-06-12T00:21:42Z",
            "closed_at": null,
            "author_association": "NONE",
            "body": "Hi is there any doc on requirements?  I'm running tensor flow with keras and I get errors on both python 2.7 and python 3.5.\r\n\r\nAny help would be appreciated, thank you!"
        }
    },
    {
        "id": 1673311684,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDE2NzMzMTE2ODQ=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1673311684",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-06-11T08:43:18Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/21",
            "id": 294334011,
            "node_id": "MDU6SXNzdWUyOTQzMzQwMTE=",
            "number": 21,
            "title": "ValueError: input shapes: [9,9,3,64], [9,9,64,3].",
            "user": {
                "login": "Heidisnaps",
                "id": 28799179,
                "node_id": "MDQ6VXNlcjI4Nzk5MTc5",
                "avatar_url": "https://avatars2.githubusercontent.com/u/28799179?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Heidisnaps",
                "html_url": "https://github.com/Heidisnaps",
                "followers_url": "https://api.github.com/users/Heidisnaps/followers",
                "following_url": "https://api.github.com/users/Heidisnaps/following{/other_user}",
                "gists_url": "https://api.github.com/users/Heidisnaps/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Heidisnaps/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Heidisnaps/subscriptions",
                "organizations_url": "https://api.github.com/users/Heidisnaps/orgs",
                "repos_url": "https://api.github.com/users/Heidisnaps/repos",
                "events_url": "https://api.github.com/users/Heidisnaps/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Heidisnaps/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 23,
            "created_at": "2018-02-05T10:00:35Z",
            "updated_at": "2018-06-11T15:39:33Z",
            "closed_at": "2018-02-21T16:13:56Z",
            "author_association": "NONE",
            "body": "$ python main.py \"input2.jpg\" --scale=2 --model=\"sr\"\r\n\r\nUsing TensorFlow backend.\r\nOld Size :  (445, 676, 3)\r\nNew Size : (890, 1352, 3)\r\nNumber of patches = 1187635, Patch Shape = (8, 8)\r\nSaving intermediate image.\r\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [9,9,64,3]."
        }
    },
    {
        "id": 1673311682,
        "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MTY3MzMxMTY4Mg==",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1673311682",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "mentioned",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-06-11T08:43:18Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/21",
            "id": 294334011,
            "node_id": "MDU6SXNzdWUyOTQzMzQwMTE=",
            "number": 21,
            "title": "ValueError: input shapes: [9,9,3,64], [9,9,64,3].",
            "user": {
                "login": "Heidisnaps",
                "id": 28799179,
                "node_id": "MDQ6VXNlcjI4Nzk5MTc5",
                "avatar_url": "https://avatars2.githubusercontent.com/u/28799179?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Heidisnaps",
                "html_url": "https://github.com/Heidisnaps",
                "followers_url": "https://api.github.com/users/Heidisnaps/followers",
                "following_url": "https://api.github.com/users/Heidisnaps/following{/other_user}",
                "gists_url": "https://api.github.com/users/Heidisnaps/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Heidisnaps/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Heidisnaps/subscriptions",
                "organizations_url": "https://api.github.com/users/Heidisnaps/orgs",
                "repos_url": "https://api.github.com/users/Heidisnaps/repos",
                "events_url": "https://api.github.com/users/Heidisnaps/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Heidisnaps/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 23,
            "created_at": "2018-02-05T10:00:35Z",
            "updated_at": "2018-06-11T15:39:33Z",
            "closed_at": "2018-02-21T16:13:56Z",
            "author_association": "NONE",
            "body": "$ python main.py \"input2.jpg\" --scale=2 --model=\"sr\"\r\n\r\nUsing TensorFlow backend.\r\nOld Size :  (445, 676, 3)\r\nNew Size : (890, 1352, 3)\r\nNumber of patches = 1187635, Patch Shape = (8, 8)\r\nSaving intermediate image.\r\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [9,9,64,3]."
        }
    },
    {
        "id": 1673119754,
        "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDE2NzMxMTk3NTQ=",
        "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/events/1673119754",
        "actor": {
            "login": "titu1994",
            "id": 3048602,
            "node_id": "MDQ6VXNlcjMwNDg2MDI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/3048602?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/titu1994",
            "html_url": "https://github.com/titu1994",
            "followers_url": "https://api.github.com/users/titu1994/followers",
            "following_url": "https://api.github.com/users/titu1994/following{/other_user}",
            "gists_url": "https://api.github.com/users/titu1994/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/titu1994/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/titu1994/subscriptions",
            "organizations_url": "https://api.github.com/users/titu1994/orgs",
            "repos_url": "https://api.github.com/users/titu1994/repos",
            "events_url": "https://api.github.com/users/titu1994/events{/privacy}",
            "received_events_url": "https://api.github.com/users/titu1994/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "subscribed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-06-11T06:53:37Z",
        "issue": {
            "url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21",
            "repository_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution",
            "labels_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21/labels{/name}",
            "comments_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21/comments",
            "events_url": "https://api.github.com/repos/titu1994/Image-Super-Resolution/issues/21/events",
            "html_url": "https://github.com/titu1994/Image-Super-Resolution/issues/21",
            "id": 294334011,
            "node_id": "MDU6SXNzdWUyOTQzMzQwMTE=",
            "number": 21,
            "title": "ValueError: input shapes: [9,9,3,64], [9,9,64,3].",
            "user": {
                "login": "Heidisnaps",
                "id": 28799179,
                "node_id": "MDQ6VXNlcjI4Nzk5MTc5",
                "avatar_url": "https://avatars2.githubusercontent.com/u/28799179?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Heidisnaps",
                "html_url": "https://github.com/Heidisnaps",
                "followers_url": "https://api.github.com/users/Heidisnaps/followers",
                "following_url": "https://api.github.com/users/Heidisnaps/following{/other_user}",
                "gists_url": "https://api.github.com/users/Heidisnaps/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Heidisnaps/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Heidisnaps/subscriptions",
                "organizations_url": "https://api.github.com/users/Heidisnaps/orgs",
                "repos_url": "https://api.github.com/users/Heidisnaps/repos",
                "events_url": "https://api.github.com/users/Heidisnaps/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Heidisnaps/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 23,
            "created_at": "2018-02-05T10:00:35Z",
            "updated_at": "2018-06-11T15:39:33Z",
            "closed_at": "2018-02-21T16:13:56Z",
            "author_association": "NONE",
            "body": "$ python main.py \"input2.jpg\" --scale=2 --model=\"sr\"\r\n\r\nUsing TensorFlow backend.\r\nOld Size :  (445, 676, 3)\r\nNew Size : (890, 1352, 3)\r\nNumber of patches = 1187635, Patch Shape = (8, 8)\r\nSaving intermediate image.\r\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 3 and 64 for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [9,9,64,3]."
        }
    }
]